### ISSUE TITLE
Resource pack is gone

### ISSUE THREAD

**Issue by kalamees123** [MecCreeper/Real-Life-Minecraft#1]
I downloaded zip file 0.2.4.0 and when i added it to minecraft it didn't work.

**Comment by MecCreeper** [comment]
You probably downloaded _github master file_ of resource pack (0.2.4.0).

**Solution nr 1:**
If you download from release folder then please click on "download" button.

**Solution nr 2:**
1. Download ZIP file.
2. Open minecraft resource pack folder.
3. Add zip file. (Delete older "Real Life Minecraft" resource pack ZIP version)
4. Done.

**Solution nr 3:**
1. Click on start button.
2. Write %appdata%.
3. Open folder .minecraft.
4. Open folder: resourcepacks.
5. Add resource pack ZIP file.
6. Open minecraft.
7. Select resource pack.
8. Enjoy!

Thank you for your feedback!
